'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Text, useSitecore, Link, Image, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useCountUp, useMagnetic } from 'lib/motion';
import { EditingEmpty } from 'lib/editing-empty';
import { useState, useRef, useEffect } from 'react';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Link', value: Link },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'lib/motion',
    exports: [
      { name: 'useCountUp', value: useCountUp },
      { name: 'useMagnetic', value: useMagnetic },
    ]
  },
  {
    module: 'lib/editing-empty',
    exports: [
      { name: 'EditingEmpty', value: EditingEmpty },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
