// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Text, Image, AppPlaceholder, RichText, Link as Link_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import { EditingEmpty } from 'lib/editing-empty';
import componentMap from '.sitecore/component-map';
import Link from 'next/link';
import { ThemeToggle } from 'src/ui/theme-toggle';
import { MobileNav } from 'src/site/MobileNav';
import { headerNav, footerNav } from 'src/site/navigation';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'Image', value: Image },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'lib/editing-empty',
    exports: [
      { name: 'EditingEmpty', value: EditingEmpty },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'src/ui/theme-toggle',
    exports: [
      { name: 'ThemeToggle', value: ThemeToggle },
    ]
  },
  {
    module: 'src/site/MobileNav',
    exports: [
      { name: 'MobileNav', value: MobileNav },
    ]
  },
  {
    module: 'src/site/navigation',
    exports: [
      { name: 'headerNav', value: headerNav },
      { name: 'footerNav', value: footerNav },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
